name: DEV UI Tests

on:
  workflow_dispatch:

jobs:
  ui_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Get UI Tests Repository
      uses: actions/checkout@v4
      with:
        repository: Mubarak-Monsuru/Python
        persist-credentials: true
        submodules: recursive
        ssh-key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: ./Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # Specify the Python version you need
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip &&
        cd ./qa-automation && \
        pip install -r requirements.txt && \
        playwright install-deps && \
        playwright install && \
        playwright install-deps && playwright install

    - name: Run the automation script
      run: |
        pwd && ls -all && cd ./Python && ls -all && cd script && \
        xvfb-run --server-args='-screen 0, 1920x1080x24' python -u sky_dev_qa_automation.py
